multiplayer-flag: true

spring:
  datasource:
    url: jdbc:postgresql://34.23.192.72:2345/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${sm://db-password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: imperium
    default-schema: imperium
  h2:
    console:
      enabled: true # Console available at http://localhost:8080/h2-console

  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: 1057996542369345588
            client-secret: ${sm://discord-client-secret}
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            scope:
              - identify
            redirectUri: "{baseUrl}/login/oauth2/code/discord"
            clientName: Imperium client
            redirectOverrideScheme: SET_BY_ENV_VARIABLE
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            userNameAttribute: username

google:
  api:
    key: ${sm://sheets-api-key}

server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

