multiplayer-flag: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imperium
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Ok03TkcHjY96
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: imperium
    default-schema: imperium
  cloud:
    gcp:
      secretmanager:
        enabled: false


  security:
    oauth2:
      client:
        registration:
          discord:
            client-secret: SET_BY_ENV_VARIABLE
            client-id: 1071564705786757200

