multiplayer-flag: true

spring:
  datasource:
    password: SET_BY_ENV_VARIABLE
  cloud:
    gcp:
      secretmanager:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          discord:
            client-secret: SET_BY_ENV_VARIABLE

google:
  api:
    key: SET_BY_ENV_VARIABLE