runtime: java17
instance_class: F2

handlers:
- url: /.*
  secure: always
  script: auto

automatic_scaling:
  max_instances: 2

env_variables:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_REDIRECTSCHEMEOVERRIDE: "https"