runtime: java17
instance_class: F2

handlers:
- url: /api/.*
  secure: always
  script: auto

- url: /
  secure: always
  script: auto

- url: /favicon.ico
  secure: always
  script: auto

- url: /images/.*
  secure: always
  script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.6
  max_concurrent_requests: 100

env_variables:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DISCORD_REDIRECTSCHEMEOVERRIDE: "https"