-- PLANTATION_NEGATIVE_LOYALTY (-2 loyalty per plantation) relies on REQUIRES_PLAYER_IS_LINCOLN requirement set.
-- Add LEADER_IMP_<modName> as another leader that satisfies this requirement.
INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType)
VALUES ('LINCOLN_<modName>_REQUIREMENTS', 'REQUIREMENT_PLAYER_LEADER_TYPE_MATCHES');

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('LINCOLN_<modName>_REQUIREMENTS', 'LeaderType', 'LEADER_IMP_<modName>');

UPDATE RequirementSets
SET RequirementSetType = 'REQUIREMENTSET_TEST_ANY'
WHERE RequirementSetId = 'REQUIRES_PLAYER_IS_LINCOLN';

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('REQUIRES_PLAYER_IS_LINCOLN', 'LINCOLN_<modName>_REQUIREMENTS');
-- Add new modifiers for creating free melee units when building (German) Hansa and (Gallic) Oppidum.
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
VALUES
('TRAIT_LINCOLN_HANSA_FREE_MELEE_UNIT',
'MODIFIER_PLAYER_DISTRICT_ADJUST_PLAYER_DISTRICT_AND_BUILDINGS_CREATE_UNIT_WITH_ABILITY_BY_CLASS_GREAT_NEGOTIATORS'),
('TRAIT_LINCOLN_OPPIDUM_FREE_MELEE_UNIT',
'MODIFIER_PLAYER_DISTRICT_ADJUST_PLAYER_DISTRICT_AND_BUILDINGS_CREATE_UNIT_WITH_ABILITY_BY_CLASS_GREAT_NEGOTIATORS');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES
('TRAIT_LINCOLN_HANSA_FREE_MELEE_UNIT', 'DistrictType', 'DISTRICT_HANSA'),
('TRAIT_LINCOLN_HANSA_FREE_MELEE_UNIT', 'UnitPromotionClass', 'PROMOTION_CLASS_MELEE'),
('TRAIT_LINCOLN_HANSA_FREE_MELEE_UNIT', 'UnitAbilityType', 'ABILITY_LINCOLN_MELEE_UNITS'),
('TRAIT_LINCOLN_OPPIDUM_FREE_MELEE_UNIT', 'DistrictType', 'DISTRICT_OPPIDUM'),
('TRAIT_LINCOLN_OPPIDUM_FREE_MELEE_UNIT', 'UnitPromotionClass', 'PROMOTION_CLASS_MELEE'),
('TRAIT_LINCOLN_OPPIDUM_FREE_MELEE_UNIT', 'UnitAbilityType', 'ABILITY_LINCOLN_MELEE_UNITS');
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES
('TRAIT_LEADER_LINCOLN', 'TRAIT_LINCOLN_HANSA_FREE_MELEE_UNIT'),
('TRAIT_LEADER_LINCOLN', 'TRAIT_LINCOLN_OPPIDUM_FREE_MELEE_UNIT');