-- Create Apostles for Kongo also for Neighborhoods and (Greek) Acropolis'.
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType)
VALUES
    ('TRAIT_FREE_APOSTLE_FINISH_NEIGHBORHOOD', 'MODIFIER_PLAYER_DISTRICT_CREATE_UNIT'),
    ('TRAIT_FREE_APOSTLE_FINISH_ACROPOLIS', 'MODIFIER_PLAYER_DISTRICT_CREATE_UNIT');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
VALUES
    ('TRAIT_FREE_APOSTLE_FINISH_NEIGHBORHOOD', 'DistrictType', 'DISTRICT_NEIGHBORHOOD'),
    ('TRAIT_FREE_APOSTLE_FINISH_NEIGHBORHOOD', 'UnitType', 'UNIT_APOSTLE'),
    ('TRAIT_FREE_APOSTLE_FINISH_ACROPOLIS', 'DistrictType', 'DISTRICT_ACROPOLIS'),
    ('TRAIT_FREE_APOSTLE_FINISH_ACROPOLIS', 'UnitType', 'UNIT_APOSTLE');
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
VALUES
    ('TRAIT_LEADER_RELIGIOUS_CONVERT', 'TRAIT_FREE_APOSTLE_FINISH_NEIGHBORHOOD'),
    ('TRAIT_LEADER_RELIGIOUS_CONVERT', 'TRAIT_FREE_APOSTLE_FINISH_ACROPOLIS');